
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server1-deployment
  labels:
    app: server1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server1
  template:
    metadata:
      labels:
        app: server1
    spec:
      containers:
      - name: server1
        image: httpd:latest  # Replace with your actual image
        ports:
        - containerPort: 80

