
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server2-deployment
  labels:
    app: server2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server2
  template:
    metadata:
      labels:
        app: server2
    spec:
      containers:
      - name: server2
        image: httpd:latest  # Replace with your actual image
        ports:
        - containerPort: 80

